version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: always
    build: .
    command: python /code/manage.py migrate --noinput
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=music.settings.base
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      ENVIRON_SETTING: "${ENVIRON_SETTING}"
      EMAIL_PASS: "${EMAIL_PASS}"
      SECRET_KEY: "${SECRET_KEY}"
      SPOTIFY_USERNAME: "${SPOTIFY_USERNAME}"
      SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}"
      SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
volumes:
  postgres_data: