version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data2/
    networks: 
      - djangonetwork
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD}"
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8888 --settings=music.settings.base
    # command: python /code/manage.py migrate --noinput
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    links:
      - "db:db"
    depends_on:
      - db
    networks: 
      - djangonetwork
    env_file: 
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      ENVIRON_SETTING: "${ENVIRON_SETTING}"
      EMAIL_PASS: "${EMAIL_PASS}"
      SECRET_KEY: "${SECRET_KEY}"
      SPOTIFY_USERNAME: "${SPOTIFY_USERNAME}"
      SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}"
      SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
volumes:
  postgres_data:
networks:
  djangonetwork:
    driver: bridge