# Generated by Django 2.1 on 2018-08-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20180828_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name', 'artist']},
        ),
        migrations.AlterModelOptions(
            name='albumsubgenre',
            options={'ordering': ['album', '-subgenre']},
        ),
        migrations.AddField(
            model_name='album',
            name='bc_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
