# Generated by Django 2.1 on 2018-08-31 21:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20180831_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cassette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='vinyl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='album',
            name='bc_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='album',
            name='primary_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='albums.PrimaryGenre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='wiki_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
