# Generated by Django 2.1 on 2018-09-09 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20180905_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='primarygenre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subgenre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='album',
            name='amazon_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='album',
            name='current_rating',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='primarygenre',
            name='spotify_playlist',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='subgenre',
            name='spotify_playlist',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='albumgroup',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='albums.Album'),
        ),
        migrations.AddField(
            model_name='albumgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='albums.Group'),
        ),
    ]
