# Generated by Django 2.1 on 2018-09-13 03:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20180909_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandcampSubgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ListenURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify', models.URLField(blank=True, null=True)),
                ('itunes', models.URLField(blank=True, null=True)),
                ('bandcamp', models.URLField(blank=True, null=True)),
                ('amazon', models.URLField(blank=True, null=True)),
                ('soundcloud', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=256)),
                ('artist_name', models.CharField(max_length=250)),
                ('genre', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiSubgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='discogs_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='album',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='seen_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgenre',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='current_rating',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listenurl',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_urls', to='albums.Album'),
        ),
    ]
