# Generated by Django 2.1 on 2018-10-03 15:31

from django.db import migrations

def transfer_urls(apps, schema_editor):
    ListenURL = apps.get_model('albums', 'ListenURL')
    Album = apps.get_model('albums', 'Album')
    AlbumArtist = apps.get_model('albums', 'AlbumArtist')

    for url in ListenURL.objects.all():
        album = url.album
        album.itunes_url = url.itunes
        album.spotify_url = url.spotify
        album.soundcloud_url = url.soundcloud
        album.youtube_url = url.youtube
        album.save()

    for album in Album.objects.all():
        AlbumArtist.objects.create(
            album=album,
            artist=album.artist
        )

    


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_auto_20181003_1531'),
    ]

    operations = [
        migrations.RunPython(transfer_urls)
    ]
