# Generated by Django 2.1 on 2018-10-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_auto_20181003_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='soudncloud_url',
            new_name='soundcloud_url',
        ),
        migrations.AddField(
            model_name='song',
            name='track_length',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='track_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
