# Generated by Django 2.1 on 2018-10-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_auto_20181004_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_num', models.IntegerField()),
                ('resolved', models.BooleanField(default=False)),
                ('selected_issue', models.TextField()),
                ('description', models.TextField()),
                ('reporter', models.TextField()),
                ('page', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_art_primary_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_art_secondary_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_art_tertiary_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
