# Generated by Django 2.1 on 2018-10-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_reportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_art_primary_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_art_secondary_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_art_tertiary_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='reportissue',
            name='page',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportissue',
            name='report',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportissue',
            name='selected_issue',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
