# Generated by Django 2.1.5 on 2019-09-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_auto_20190115_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='playlists',
            field=models.TextField(blank=True, null=True),
        ),
    ]
